#!/bin/bash

#Colours
greenColour="\e[0;32m\033[1m"
endColour="\033[0m\e[0m"
redColour="\e[0;31m\033[1m"
blueColour="\e[0;34m\033[1m"
yellowColour="\e[0;33m\033[1m"
purpleColour="\e[0;35m\033[1m"
turquoiseColour="\e[0;36m\033[1m"
grayColour="\e[0;37m\033[1m"

ctrl_c(){
	echo -e "\n\n${redColour}[!] Aborting update...${endColour}\n"
	tput cnorm; exit 1
}

# Ctrl+C
trap ctrl_c INT

path="$(find ~ -type d -name kromaTool)"

updateTools(){
	tput civis
	echo -e "\n${greenColour}[+]${endColour} ${grayColour}Checking for pending updates...${endColour}\n"

	cd "$path"
	git pull > checker.txt 2>/dev/null

	checker="$(grep "Updating" checker.txt)"

	if [ "$checker" ]; then
		for file in tools/*; do
			route="$(realpath "$file")"

			chmod +x "$route"
			ln -sf "$route" -t /usr/bin/
		done
		echo -e "${greenColour}[+]${endColour} ${grayColour}Update ${greenColour}successfully${endColour} ${grayColour}completed!${endColour}\n"
	else
		echo -e "${greenColour}[+]${endColour} ${grayColour}$(cat checker.txt)${endColour}\n"
	fi
	rm checker.txt
	tput cnorm && exit 0
}

if [ "$path" ]; then
	updateTools
else
	search_path="$(find / -type d -name kromaTool)"
	cd "$search_path" && updateTools
fi
