#!/bin/bash

#Colours
greenColour="\e[0;32m\033[1m"
endColour="\033[0m\e[0m"
redColour="\e[0;31m\033[1m"
blueColour="\e[0;34m\033[1m"
yellowColour="\e[0;33m\033[1m"
purpleColour="\e[0;35m\033[1m"
turquoiseColour="\e[0;36m\033[1m"
grayColour="\e[0;37m\033[1m"

ctrl_c(){
	echo -e "\n\n${redColour}[!] Aborting update...${endColour}\n"
	tput cnorm; exit 1
}

# Ctrl+C
trap ctrl_c INT

search_path="$(find / -type d -name kromaTool 2>/dev/null | awk 'NR==1{print $0}')"

updateTools(){
	tput civis
	echo -e "\n${greenColour}[+]${endColour} ${grayColour}Checking for pending updates...${endColour}\n"
	echo -e "${yellowColour}[!]${endColour} ${grayColour}This may take a few minutes${endColour}\n"

	cd "$search_path"

	git pull > checker.txt 2>/dev/null && sleep 2

	checker="$(grep "Updating" checker.txt)"

	if [ "$checker" ]; then
		for file in $search_path/tools/*; do

			route="$(realpath $file)"

			chmod +x "$route"
			ln -sf "$route" /usr/bin/
		done
		echo -e "${greenColour}[+]${endColour} ${grayColour}Update ${greenColour}successfully${endColour} ${grayColour}completed!${endColour}\n"
	else
		echo -e "${greenColour}[+]${endColour} ${grayColour}$(cat checker.txt)${endColour}\n"
	fi
	rm checker.txt
	tput cnorm && exit 0
}

if [ "$search_path" ]; then
	updateTools
else
	echo -e "\n\n${redColour}[!] ERROR: Aborting update...${endColour}\n"
	echo -e "${redColour}[!] Cannot find kromaTool folder${endColour}\n"
fi
